In [4]:
import torch

x = torch.empty(1)
print(x)

tensor([1.4013e-45])


In [5]:
x = torch.empty(3)
print(x)


tensor([0.0000e+00, 4.7684e-06, 1.6816e-44])


In [6]:
x = torch.empty(2, 3)
print(x)

tensor([[0.0000e+00, 0.0000e+00, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 5.9694e-39]])


In [10]:
x = torch.zeros(2, 2)
print(x)

tensor([[0., 0.],
        [0., 0.]])


In [11]:
x = torch.ones(2, 2)
print(x)

tensor([[1., 1.],
        [1., 1.]])


In [14]:
x = torch.rand(2, 2, dtype=torch.double)
print(x)

tensor([[0.8258, 0.3813],
        [0.2654, 0.3614]], dtype=torch.float64)


In [16]:
print(x.dtype)
print(x.size())

torch.float64
torch.Size([2, 2])


In [17]:
x = torch.tensor([1, 2, 3, 4, 5, 0.5])
print(x)

tensor([1.0000, 2.0000, 3.0000, 4.0000, 5.0000, 0.5000])


In [23]:
##tensor operations
x = torch.rand(2, 2)
y = torch.rand(2, 2)

print(x)
print(y)

##Addition
z = x+y
x = torch.add(x, y)
print(z)

y.add_(x) ## underscore means the variable y will be modified
print(y)

#Subtraction
z = x - y
z = torch.subtract(x, y)
print(z)
y.subtract_(x)
print(y)

#Multiplication
z = x * y
z = torch.mul(x, y)
print(z)
y.mul_(x)
print(y)

##And So On

tensor([[0.0859, 0.4819],
        [0.1032, 0.9675]])
tensor([[0.8614, 0.0754],
        [0.2739, 0.1763]])
tensor([[0.9474, 0.5574],
        [0.3771, 1.1438]])
tensor([[1.8088, 0.6328],
        [0.6510, 1.3201]])
tensor([[-0.8614, -0.0754],
        [-0.2739, -0.1763]])
tensor([[0.8614, 0.0754],
        [0.2739, 0.1763]])
tensor([[0.8161, 0.0420],
        [0.1033, 0.2016]])
tensor([[0.8161, 0.0420],
        [0.1033, 0.2016]])


In [26]:
#tensor slicing
x = torch.rand(5, 3)
print(x)
print(x[:, 0])
print(x[1, :])
print(x[1, 1]) #remove tensor encapsulation. Works for only one item

#reshape tensor
x = torch.rand(4, 4)
print(x)
y = x.view(16) #1D array with 16 elements
print(y)
y = x.view(-1, 8) #Pytorch will calculate value for the parameter where -1 is assigned
print(y)
print(y.size())

tensor([[0.0907, 0.0395, 0.8147],
        [0.2061, 0.4408, 0.7821],
        [0.8085, 0.4440, 0.0904],
        [0.3227, 0.6695, 0.9401],
        [0.1178, 0.7412, 0.2675]])
tensor([0.0907, 0.2061, 0.8085, 0.3227, 0.1178])
tensor([0.2061, 0.4408, 0.7821])
tensor(0.4408)
tensor([[0.7430, 0.3688, 0.4598, 0.7869],
        [0.9421, 0.1833, 0.0253, 0.3283],
        [0.3466, 0.7929, 0.2508, 0.9426],
        [0.2707, 0.5746, 0.7918, 0.4286]])
tensor([0.7430, 0.3688, 0.4598, 0.7869, 0.9421, 0.1833, 0.0253, 0.3283, 0.3466,
        0.7929, 0.2508, 0.9426, 0.2707, 0.5746, 0.7918, 0.4286])
tensor([[0.7430, 0.3688, 0.4598, 0.7869, 0.9421, 0.1833, 0.0253, 0.3283],
        [0.3466, 0.7929, 0.2508, 0.9426, 0.2707, 0.5746, 0.7918, 0.4286]])
torch.Size([2, 8])


In [29]:
#tensor to nummpy
import numpy as np

a = torch.ones(5)
print(a)
b = a.numpy() # b and a will share the same memory location. So if value of a is changed than value of b will also be changed
print(b)
print(type(b))

a[4] = 2
print(a)
print(b)

#Vice versa
a = np.ones(5)
print(a)
b = torch.from_numpy(a) # b and a will share the same memory location. So if value of a is changed than value of b will also be changed
print(b)
print(type(b))

a[4] = 2
print(a)
print(b)

tensor([1., 1., 1., 1., 1.])
[1. 1. 1. 1. 1.]
<class 'numpy.ndarray'>
tensor([1., 1., 1., 1., 2.])
[1. 1. 1. 1. 2.]
[1. 1. 1. 1. 1.]
tensor([1., 1., 1., 1., 1.], dtype=torch.float64)
<class 'torch.Tensor'>
[1. 1. 1. 1. 2.]
tensor([1., 1., 1., 1., 2.], dtype=torch.float64)


In [30]:
x = torch.ones(5, requires_grad=True) #It will tell pytorch to use gradient on this tensor in further calculation
print(x)

tensor([1., 1., 1., 1., 1.], requires_grad=True)
